[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    spec = "cypress/e2e/smoke.cy.ts"

  [plugins.inputs.preBuild]
    enable = true
    start = 'netlify dev'
    wait-on = 'http://localhost:5173'
    wait-on-timeout = '30'

