[build]
command = "npm run build"
publish = "build"
  [build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"


[[plugins]]
package = "netlify-plugin-cypress"
    
  [plugins.inputs]
  record = true
  spec = "cypress/integrations/firstTest.cy.ts"
  browser = "chrome"
  configFile = "cypress.netlify.config.ts"

  [plugins.inputs.preBuild]
    enable = true
    start = 'npm start'
    wait-on = 'http://localhost:3000'
    wait-on-timeout = '30'

  [plugins.inputs.postBuild]
    enable = true