[build]
  command = "npm run build &&  npm run cy:run"
  publish = "build"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  
  [plugins.inputs]
    record = true
    spec = "cypress/e2e/firstTest.cy.ts"
    configFile = "cypress.netlify.config.js"

